#!/usr/bin/env python3
"""
Preprocess DIPS-Plus structural complexes into EdgePPI Stage 1 CSVs + contact maps.

Input layout (on production server):
  /data/dbs/dips_pdb/
    pairs-postprocessed-train.txt   — relative paths to .dill files
    pairs-postprocessed-val.txt
    {subdir}/{pdb}.dill             — DIPS-Plus pair objects

Each .dill file contains:
  pair.df0        atom-level DataFrame for chain A (columns: residue, resname, x,y,z, atom_name, ...)
  pair.df1        atom-level DataFrame for chain B
  pair.sequences  dict with 'l_b' and 'r_b' sequence strings (not always present)

Output:
  {out_dir}/stage1/
    dips_train.csv      — (seq_a, seq_b, label=1, contact_map)
    dips_val.csv
  {out_dir}/stage1/contact_maps/
    {split}_{idx}.npy   — (L_A, L_B) float32 binary contact map (Cα-Cα ≤ threshold)

Design notes
------------
Contact map definition:
  contact_map[i, j] = 1 if Cα of residue i (chain A) is within
  CONTACT_THRESHOLD Å of Cα of residue j (chain B).

  We use 8 Å (Cα-Cα) — standard in contact prediction literature.
  This is slightly more permissive than dips_interface.py's 6 Å,
  to capture second-shell interface residues that may matter for
  energy transmission.

Only positive pairs are generated (all DIPS complexes are interacting).
Negative pairs for Stage 1 are generated by cross-pairing in build_stage1_combined.py.

Parallelism:
  ProcessPoolExecutor for CPU-bound dill loading and distance computation.
  Adjust --num_workers to number of available CPU cores.

Usage:
    python scripts/preprocess_dips.py \
        --dips_dir   /data/dbs/dips_pdb \
        --out_dir    data \
        --threshold  8.0 \
        --max_pairs  40000 \
        --num_workers 32
"""

from __future__ import annotations

import argparse
import logging
import os
import pickle
from concurrent.futures import ProcessPoolExecutor, as_completed
from typing import Dict, List, Optional, Tuple

import numpy as np
import pandas as pd

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
logger = logging.getLogger(__name__)

STANDARD_AA = set("ACDEFGHIKLMNPQRSTVWY")

AA3TO1: Dict[str, str] = {
    "ALA": "A", "ARG": "R", "ASN": "N", "ASP": "D", "CYS": "C",
    "GLN": "Q", "GLU": "E", "GLY": "G", "HIS": "H", "ILE": "I",
    "LEU": "L", "LYS": "K", "MET": "M", "PHE": "F", "PRO": "P",
    "SER": "S", "THR": "T", "TRP": "W", "TYR": "Y", "VAL": "V",
    "MSE": "M",   # selenomethionine → Met
    "HSD": "H", "HSE": "H", "HSP": "H",   # HIS variants
    "UNK": "G",   # unknown → Gly (minimally disruptive)
}


# ---------------------------------------------------------------------------
# DIPS dill parsing
# ---------------------------------------------------------------------------

def _df_to_residue_seqcoords(
    df: "pd.DataFrame",
    heavy_atom: bool = False,
) -> Optional[Tuple[str, np.ndarray]]:
    """
    Extract per-residue sequence and coordinates from a DIPS atom DataFrame.

    Args:
        df:          DIPS atom DataFrame (pair.df0 or pair.df1).
        heavy_atom:  If False (default), return Cα-only coords — shape (L, 3).
                     If True, return all heavy-atom coords per residue as a
                     ragged list of arrays — shape List[(n_heavy_i, 3)].
                     Used for minimum-heavy-atom-distance contact maps.

    Returns:
        (sequence_string, coords) where coords is:
          - (L, 3) float32 ndarray  when heavy_atom=False
          - List[(n_i, 3) float32]  when heavy_atom=True  (length L)
        or None on error.
    """
    # Exclude hydrogen atoms (atom names starting with H or 1H/2H etc.)
    _HYDROGEN = {"H", "1H", "2H", "3H", "HN", "HA", "HB", "HG", "HD", "HE", "HZ", "HH"}

    try:
        # ── Cα-only path (fast) ───────────────────────────────────────────────
        if not heavy_atom:
            ca_mask = df["atom_name"].str.strip() == "CA"
            df_ca = df[ca_mask]
            if len(df_ca) == 0:
                df_ca = df.groupby(["chain", "residue"], sort=False).first().reset_index()
            else:
                df_ca = df_ca.drop_duplicates(subset=["chain", "residue"], keep="first")
            df_ca = df_ca.sort_values("residue").reset_index(drop=True)

            seq = "".join(AA3TO1.get(r.strip().upper(), "G") for r in df_ca["resname"])
            seq = "".join(c if c in STANDARD_AA else "G" for c in seq)
            coords = df_ca[["x", "y", "z"]].values.astype(np.float32)

            if len(seq) < 5 or len(coords) != len(seq):
                return None
            return seq, coords

        # ── Heavy-atom path ───────────────────────────────────────────────────
        # Exclude hydrogens; deduplicate residues by sorted (chain, residue).
        non_h = ~df["atom_name"].str.strip().str.upper().str.match(r"^H|^[123]H")
        df_heavy = df[non_h].copy()

        # Build ordered residue list from Cα atoms (ensures sequence order)
        ca_mask = df["atom_name"].str.strip() == "CA"
        df_ca = df[ca_mask].drop_duplicates(subset=["chain", "residue"], keep="first")
        df_ca = df_ca.sort_values("residue").reset_index(drop=True)

        seq = "".join(AA3TO1.get(r.strip().upper(), "G") for r in df_ca["resname"])
        seq = "".join(c if c in STANDARD_AA else "G" for c in seq)

        # For each residue in order, collect all heavy-atom (x,y,z) coords.
        # Fall back to Cα if no heavy atoms found for a residue.
        residues = list(df_ca["residue"])
        grouped = df_heavy.groupby("residue")
        heavy_coords_per_res: List[np.ndarray] = []
        for res_id in residues:
            if res_id in grouped.groups:
                grp = grouped.get_group(res_id)
                heavy_coords_per_res.append(grp[["x", "y", "z"]].values.astype(np.float32))
            else:
                # Fallback: use Cα row from df_ca
                row = df_ca[df_ca["residue"] == res_id]
                heavy_coords_per_res.append(row[["x", "y", "z"]].values.astype(np.float32))

        if len(seq) < 5 or len(heavy_coords_per_res) != len(seq):
            return None
        return seq, heavy_coords_per_res

    except Exception:
        return None


def _compute_contact_map(
    coords_a: np.ndarray,
    coords_b: np.ndarray,
    threshold: float = 8.0,
) -> np.ndarray:
    """
    Compute binary Cα-Cα contact map.

    contact_map[i, j] = 1 iff ||coords_a[i] - coords_b[j]||₂ ≤ threshold

    Returns:
        (L_A, L_B) float32 array
    """
    diff = coords_a[:, None, :] - coords_b[None, :, :]  # (L_A, L_B, 3)
    dist2 = (diff ** 2).sum(axis=-1)                     # (L_A, L_B)
    return (dist2 <= threshold ** 2).astype(np.float32)


def _compute_heavy_atom_contact_map(
    heavy_a: List[np.ndarray],   # L_A × (n_i, 3)
    heavy_b: List[np.ndarray],   # L_B × (n_j, 3)
    threshold: float = 4.5,
) -> np.ndarray:
    """
    Compute binary contact map based on minimum inter-residue heavy-atom distance.

    contact_map[i, j] = 1 iff min over all heavy atoms k in residue i and
                              l in residue j of ||atom_k - atom_l||₂ ≤ threshold

    4.5 Å captures:
      - Direct van der Waals contacts (~3.5 Å)
      - Hydrogen bonds (~2.0–3.5 Å N-O / O-O)
      - Salt bridges (~4.0 Å)
    Excludes second-shell residues (typically 5–8 Å Cα-Cα) that are coupled to
    the interface but not directly touching it.

    Memory: computed residue-pair by residue-pair to avoid O(N_atoms²) broadcast.
    For L=512 with ~8 atoms/residue: negligible compared to Cα-only approach.

    Returns:
        (L_A, L_B) float32 array
    """
    L_A = len(heavy_a)
    L_B = len(heavy_b)
    cmap = np.zeros((L_A, L_B), dtype=np.float32)
    thresh2 = threshold ** 2

    for i, atoms_i in enumerate(heavy_a):
        for j, atoms_j in enumerate(heavy_b):
            # (n_i, 1, 3) - (1, n_j, 3) → (n_i, n_j)
            diff = atoms_i[:, None, :] - atoms_j[None, :, :]
            min_d2 = (diff ** 2).sum(axis=-1).min()
            if min_d2 <= thresh2:
                cmap[i, j] = 1.0

    return cmap


def _process_dill(args: Tuple) -> Optional[Dict]:
    """
    Worker function: load one DIPS-Plus .dill file and extract data.

    Args:
        (dill_path, pair_key, threshold, max_seq_len, use_heavy_atom)

    Returns:
        dict with keys: seq_a, seq_b, contact_map (np.ndarray), pair_key
        or None on failure.
    """
    dill_path, pair_key, threshold, max_seq_len, use_heavy_atom = args

    try:
        import dill
        with open(dill_path, "rb") as f:
            pair = dill.load(f)
    except Exception:
        return None

    try:
        df0 = pair.df0
        df1 = pair.df1
    except AttributeError:
        return None

    res_a = _df_to_residue_seqcoords(df0, heavy_atom=use_heavy_atom)
    res_b = _df_to_residue_seqcoords(df1, heavy_atom=use_heavy_atom)

    if res_a is None or res_b is None:
        return None

    seq_a, coords_a = res_a
    seq_b, coords_b = res_b

    # Clip to max length
    seq_a = seq_a[:max_seq_len]
    coords_a = coords_a[:max_seq_len]
    seq_b = seq_b[:max_seq_len]
    coords_b = coords_b[:max_seq_len]

    if use_heavy_atom:
        contact_map = _compute_heavy_atom_contact_map(coords_a, coords_b, threshold)
    else:
        contact_map = _compute_contact_map(coords_a, coords_b, threshold)

    n_contacts = int(contact_map.sum())
    if n_contacts == 0:
        return None

    return {
        "seq_a": seq_a,
        "seq_b": seq_b,
        "contact_map": contact_map,
        "pair_key": pair_key,
        "n_contacts": n_contacts,
    }


# ---------------------------------------------------------------------------
# Main processing loop
# ---------------------------------------------------------------------------

def process_split(
    dips_dir: str,
    split_file: str,
    out_dir: str,
    split_name: str,
    threshold: float = 8.0,
    max_seq_len: int = 512,
    max_pairs: int = 0,
    num_workers: int = 32,
    use_heavy_atom: bool = False,
) -> None:
    """
    Process one DIPS-Plus split (train or val).

    Saves:
      {out_dir}/stage1/dips_{split_name}.csv
      {out_dir}/stage1/contact_maps/dips_{split_name}_{idx}.npy

    Args:
        use_heavy_atom: If True, use minimum heavy-atom distance for contacts
                        instead of Cα-Cα.  Recommended threshold: 4.5 Å.
                        Produces sparser, more physically precise interface masks
                        for Stage 1b training.  NOTE: ~4× slower than Cα-only.
                        Output files go to contact_maps_heavy/ to avoid
                        overwriting existing Cα contact maps.
    """
    subdir = "contact_maps_heavy" if use_heavy_atom else "contact_maps"
    contact_map_dir = os.path.join(out_dir, "stage1", subdir)
    os.makedirs(contact_map_dir, exist_ok=True)

    if not os.path.exists(split_file):
        logger.warning(f"Split file not found: {split_file}")
        return

    # Read relative paths
    with open(split_file) as f:
        rel_paths = [l.strip() for l in f if l.strip()]

    if max_pairs > 0:
        rel_paths = rel_paths[:max_pairs]

    mode_str = f"heavy-atom ≤{threshold}Å" if use_heavy_atom else f"Cα-Cα ≤{threshold}Å"
    logger.info(
        f"\n=== Processing DIPS-Plus {split_name} "
        f"({len(rel_paths):,} pairs, contact={mode_str}) ==="
    )

    jobs = []
    for rel in rel_paths:
        full_path = os.path.join(dips_dir, rel)
        pair_key = rel.replace("/", "_").replace(".dill", "")
        jobs.append((full_path, pair_key, threshold, max_seq_len, use_heavy_atom))

    # Process in parallel
    rows: List[Dict] = []
    failed = 0

    with ProcessPoolExecutor(max_workers=num_workers) as ex:
        futures = {ex.submit(_process_dill, j): j for j in jobs}
        for i, fut in enumerate(as_completed(futures)):
            result = fut.result()
            if result is None:
                failed += 1
            else:
                idx = len(rows)
                prefix = "dips_heavy" if use_heavy_atom else "dips"
                map_filename = f"{prefix}_{split_name}_{idx}.npy"
                map_path = os.path.join(contact_map_dir, map_filename)
                np.save(map_path, result["contact_map"])

                rows.append({
                    "seq_a": result["seq_a"],
                    "seq_b": result["seq_b"],
                    "label": 1,
                    "contact_map": map_path,
                    "pair_key": result["pair_key"],
                    "n_contacts": result["n_contacts"],
                    "len_a": len(result["seq_a"]),
                    "len_b": len(result["seq_b"]),
                })

            if (i + 1) % 1000 == 0:
                logger.info(
                    f"  Processed {i+1:,}/{len(jobs):,} | "
                    f"ok={len(rows):,} failed={failed:,}"
                )

    df = pd.DataFrame(rows)
    csv_stem = "dips_heavy" if use_heavy_atom else "dips"
    csv_path = os.path.join(out_dir, "stage1", f"{csv_stem}_{split_name}.csv")
    df.to_csv(csv_path, index=False)

    logger.info(
        f"\n  DIPS-Plus {split_name}: {len(df):,} pairs saved → {csv_path}"
        f"\n  Failed / skipped: {failed:,}"
        f"\n  Mean contacts per pair: {df['n_contacts'].mean():.1f}"
        f"\n  Mean L_A: {df['len_a'].mean():.0f}, Mean L_B: {df['len_b'].mean():.0f}"
    )

    # Print contact fraction stats
    contact_fracs = []
    for i, row in df.iterrows():
        cmap_path = row["contact_map"]
        if os.path.exists(cmap_path):
            cmap = np.load(cmap_path)
            contact_fracs.append(cmap.mean())
    if contact_fracs:
        logger.info(
            f"  Contact density: mean={np.mean(contact_fracs):.3f}, "
            f"median={np.median(contact_fracs):.3f}"
        )


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> None:
    parser = argparse.ArgumentParser(description="Preprocess DIPS-Plus for EdgePPI")
    parser.add_argument("--dips_dir",       default="/data/dbs/dips_pdb",
                        help="Path to DIPS-Plus root directory")
    parser.add_argument("--out_dir",        default="data",
                        help="Output root directory")
    parser.add_argument("--threshold",      type=float, default=8.0,
                        help="Distance threshold (Å). Cα-Cα default=8.0; heavy-atom recommended=4.5")
    parser.add_argument("--heavy_atom",     action="store_true",
                        help="Use minimum heavy-atom distance instead of Cα-Cα. "
                             "Produces sparser, more physically precise interface masks. "
                             "Recommend --threshold 4.5. ~4x slower than Cα-only.")
    parser.add_argument("--max_seq_len",    type=int,   default=512)
    parser.add_argument("--max_pairs",      type=int,   default=0,
                        help="Max pairs to process per split (0 = all)")
    parser.add_argument("--num_workers",    type=int,   default=32)
    args = parser.parse_args()

    os.makedirs(os.path.join(args.out_dir, "stage1"), exist_ok=True)

    for split_name, list_file in [
        ("train", "pairs-postprocessed-train.txt"),
        ("val", "pairs-postprocessed-val.txt"),
    ]:
        full_list = os.path.join(args.dips_dir, list_file)
        process_split(
            dips_dir=args.dips_dir,
            split_file=full_list,
            out_dir=args.out_dir,
            split_name=split_name,
            threshold=args.threshold,
            max_seq_len=args.max_seq_len,
            max_pairs=args.max_pairs,
            num_workers=args.num_workers,
            use_heavy_atom=args.heavy_atom,
        )

    logger.info("\nDIPS-Plus preprocessing complete.")


if __name__ == "__main__":
    main()


## Standard Cα-Cα contacts (fast, 8Å threshold)
## python src/dsa/preprocess_dips.py  --dips_dir /data/dbs/dips_pdb/ --out_dir  src/dsa/data/dips_output_calpha_8A --threshold 8.0 --num_workers 32